services:

  postgresql:
    container_name: postgres-portfolio
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: main-app-api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - default

volumes:
    postgresql:
#  migrations:
#    container_name: db-migrations
#    build:
#      context: .
#      dockerfile: docker/migrations/Dockerfile
